# Generated by Django 4.1 on 2022-08-31 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsavel',
            name='filho',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Filho'),
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='carteira',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeiro.carteira', verbose_name='Carteira'),
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='descricao_gasto',
            name='carteira',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeiro.carteira', verbose_name='Carteira'),
        ),
        migrations.AddField(
            model_name='descricao_gasto',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='descricao_gasto',
            name='valor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeiro.movimentacao'),
        ),
        migrations.AddField(
            model_name='carteira',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
