# Generated by Django 4.1.1 on 2022-09-08 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacao',
            name='descricao',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição'),
        ),
        migrations.DeleteModel(
            name='Descricao_gasto',
        ),
    ]
