# Generated by Django 4.1.1 on 2022-09-09 01:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0003_movimentacao_descricao_delete_descricao_gasto'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacao',
            name='data',
            field=models.DateField(default=datetime.datetime(2022, 9, 9, 1, 48, 57, 856916, tzinfo=datetime.timezone.utc), verbose_name='Data'),
        ),
    ]
