# Generated by Django 4.1.1 on 2022-09-09 12:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0004_movimentacao_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poupanca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_poupanca', models.CharField(max_length=40, verbose_name='Descrição')),
                ('saldo_poupanca', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Saldo')),
            ],
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='data',
            field=models.DateField(default=datetime.datetime(2022, 9, 9, 12, 25, 22, 262891, tzinfo=datetime.timezone.utc), verbose_name='Data'),
        ),
    ]
