# Generated by Django 4.1.1 on 2022-09-09 22:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0006_alter_movimentacao_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacao',
            name='data',
            field=models.DateField(default=datetime.datetime(2022, 9, 9, 22, 18, 46, 442925, tzinfo=datetime.timezone.utc), verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='tipo_movimentacao',
            field=models.CharField(choices=[('DESPESA', 'despesa'), ('ENTRADA', 'entrada')], default='Entrada', max_length=7),
        ),
    ]
