# Generated by Django 4.1 on 2022-09-18 20:11

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('financeiro', '0007_alter_movimentacao_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='poupanca',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='data',
            field=models.DateField(default=datetime.datetime(2022, 9, 18, 20, 11, 54, 657776, tzinfo=datetime.timezone.utc), verbose_name='Data'),
        ),
    ]
