# Generated by Django 4.1.1 on 2022-09-18 23:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0007_alter_movimentacao_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacao',
            name='data',
            field=models.DateField(default=datetime.datetime(2022, 9, 18, 23, 6, 20, 524001, tzinfo=datetime.timezone.utc), verbose_name='Data'),
        ),
    ]
